apiVersion: versions.wolfi.dev/v1
kind: VersionStream
metadata:
  name: cert-manager
spec:
  endOfLife:
    identifier: cert-manager
  versionStreamFormat: ${{name}}-${{versions.major}}.${{versions.minor}}
status:
  eolVersions:
  - eolDate: "2024-01-31"
    releaseDate: "2023-05-19"
    version: "1.12"
  - eolDate: "2023-09-12"
    releaseDate: "2023-01-11"
    version: "1.11"
  lastUpdatedTimestamp: "2024-02-27T07:30:34.183820104Z"
  latestVersion: 1.14.3
  versions:
  - eolDate: ""
    releaseDate: "2024-01-31"
    version: "1.14"
  - eolDate: ""
    releaseDate: "2023-09-12"
    version: "1.13"
