apiVersion: versions.wolfi.dev/v1
kind: VersionStream
metadata:
  name: envoy
spec:
  endOfLife:
    identifier: envoy
  versionStreamFormat: ${{name}}-${{versions.major}}.${{versions.minor}}
status:
  eolVersions:
  - eolDate: "2024-01-18"
    releaseDate: "2023-01-18"
    version: "1.25"
  - eolDate: "2023-10-19"
    releaseDate: "2022-10-19"
    version: "1.24"
  - eolDate: "2023-07-15"
    releaseDate: "2022-07-15"
    version: "1.23"
  - eolDate: "2023-04-15"
    releaseDate: "2022-04-15"
    version: "1.22"
  - eolDate: "2023-01-12"
    releaseDate: "2022-01-12"
    version: "1.21"
  - eolDate: "2022-10-05"
    releaseDate: "2021-10-05"
    version: "1.20"
  - eolDate: "2022-07-13"
    releaseDate: "2021-07-13"
    version: "1.19"
  - eolDate: "2022-04-15"
    releaseDate: "2021-04-15"
    version: "1.18"
  - eolDate: "2022-01-11"
    releaseDate: "2021-01-11"
    version: "1.17"
  - eolDate: "2021-10-08"
    releaseDate: "2020-10-08"
    version: "1.16"
  - eolDate: "2021-07-07"
    releaseDate: "2020-07-07"
    version: "1.15"
  - eolDate: "2021-04-08"
    releaseDate: "2020-04-08"
    version: "1.14"
  - eolDate: "2021-01-20"
    releaseDate: "2020-01-20"
    version: "1.13"
  - eolDate: "2020-10-31"
    releaseDate: "2019-10-31"
    version: "1.12"
  - eolDate: "2019-10-31"
    releaseDate: "2019-07-11"
    version: "1.11"
  - eolDate: "2019-07-11"
    releaseDate: "2019-04-05"
    version: "1.10"
  - eolDate: "2019-04-05"
    releaseDate: "2018-12-20"
    version: "1.9"
  - eolDate: "2018-12-20"
    releaseDate: "2018-10-04"
    version: "1.8"
  - eolDate: "2018-10-04"
    releaseDate: "2018-06-21"
    version: "1.7"
  - eolDate: "2018-06-21"
    releaseDate: "2018-03-20"
    version: "1.6"
  - eolDate: "2018-03-20"
    releaseDate: "2017-12-04"
    version: "1.5"
  - eolDate: "2017-12-04"
    releaseDate: "2017-08-24"
    version: "1.4"
  - eolDate: "2017-08-24"
    releaseDate: "2017-05-17"
    version: "1.3"
  - eolDate: "2017-05-17"
    releaseDate: "2017-03-07"
    version: "1.2"
  - eolDate: "2017-03-07"
    releaseDate: "2016-11-30"
    version: "1.1"
  - eolDate: "2016-11-30"
    releaseDate: "2016-09-12"
    version: "1.0"
  lastUpdatedTimestamp: "2024-02-26T07:30:26.953317879Z"
  latestVersion: 1.29.1
  versions:
  - eolDate: "2025-01-16"
    releaseDate: "2024-01-16"
    version: "1.29"
  - eolDate: "2024-10-19"
    releaseDate: "2023-10-19"
    version: "1.28"
  - eolDate: "2024-07-27"
    releaseDate: "2023-07-26"
    version: "1.27"
  - eolDate: "2024-04-18"
    releaseDate: "2023-04-18"
    version: "1.26"
