apiVersion: versions.wolfi.dev/v1
kind: VersionStream
metadata:
  name: kubernetes
spec:
  endOfLife:
    identifier: kubernetes
  versionStreamFormat: ${{name}}-${{versions.major}}.${{versions.minor}}
status:
  eolVersions:
  - eolDate: "2023-10-27"
    releaseDate: "2022-08-23"
    version: "1.25"
  - eolDate: "2023-07-28"
    releaseDate: "2022-05-03"
    version: "1.24"
  - eolDate: "2023-02-28"
    releaseDate: "2021-12-07"
    version: "1.23"
  - eolDate: "2022-10-28"
    releaseDate: "2021-08-04"
    version: "1.22"
  - eolDate: "2022-06-28"
    releaseDate: "2021-04-08"
    version: "1.21"
  - eolDate: "2022-02-28"
    releaseDate: "2020-12-08"
    version: "1.20"
  - eolDate: "2021-10-28"
    releaseDate: "2020-08-26"
    version: "1.19"
  - eolDate: "2021-06-18"
    releaseDate: "2020-03-25"
    version: "1.18"
  - eolDate: "2020-12-25"
    releaseDate: "2019-12-07"
    version: "1.17"
  - eolDate: "2020-08-04"
    releaseDate: "2019-09-18"
    version: "1.16"
  lastUpdatedTimestamp: "2023-12-15T07:30:21.01073315Z"
  latestVersion: 1.28.4
  versions:
  - releaseDate: "2023-08-15"
    version: "1.28"
  - releaseDate: "2023-04-11"
    version: "1.27"
  - releaseDate: "2022-12-08"
    version: "1.26"
