apiVersion: versions.wolfi.dev/v1
kind: VersionStream
metadata:
  name: nodejs
spec:
  endOfLife:
    identifier: nodejs
  versionStreamFormat: ${{name}}-${{versions.major}}
status:
  eolVersions:
  - eolDate: "2023-06-01"
    releaseDate: "2022-10-18"
    version: "19"
  - eolDate: "2022-06-01"
    releaseDate: "2021-10-19"
    version: "17"
  - eolDate: "2023-09-11"
    lts: "2021-10-26"
    releaseDate: "2021-04-20"
    version: "16"
  - eolDate: "2021-06-01"
    releaseDate: "2020-10-20"
    version: "15"
  - eolDate: "2023-04-30"
    lts: "2020-10-27"
    releaseDate: "2020-04-21"
    version: "14"
  - eolDate: "2020-06-01"
    releaseDate: "2019-10-22"
    version: "13"
  - eolDate: "2022-04-30"
    lts: "2019-10-21"
    releaseDate: "2019-04-23"
    version: "12"
  - eolDate: "2019-06-30"
    releaseDate: "2018-10-23"
    version: "11"
  - eolDate: "2021-04-30"
    lts: "2018-10-30"
    releaseDate: "2018-04-24"
    version: "10"
  - eolDate: "2018-06-30"
    releaseDate: "2017-10-31"
    version: "9"
  - eolDate: "2019-12-31"
    lts: "2017-10-31"
    releaseDate: "2017-05-30"
    version: "8"
  - eolDate: "2017-06-30"
    releaseDate: "2016-10-25"
    version: "7"
  - eolDate: "2019-04-30"
    lts: "2016-10-18"
    releaseDate: "2016-04-26"
    version: "6"
  - eolDate: "2016-06-30"
    releaseDate: "2015-10-30"
    version: "5"
  - eolDate: "2018-04-30"
    lts: "2015-10-01"
    releaseDate: "2015-09-09"
    version: "4"
  - eolDate: "1970-01-01"
    releaseDate: "2015-08-04"
    version: "3"
  - eolDate: "1970-01-01"
    releaseDate: "2015-05-04"
    version: "2"
  - eolDate: "1970-01-01"
    releaseDate: "2015-01-20"
    version: "1"
  lastUpdatedTimestamp: "2024-02-22T15:49:42.954533622Z"
  latestVersion: 21.6.2
  versions:
  - eolDate: "2024-06-01"
    releaseDate: "2023-10-17"
    version: "21"
  - eolDate: "2026-04-30"
    lts: "2023-10-24"
    releaseDate: "2023-04-18"
    version: "20"
  - eolDate: "2025-04-30"
    lts: "2022-10-25"
    releaseDate: "2022-04-19"
    version: "18"
