apiVersion: versions.wolfi.dev/v1
kind: VersionStream
metadata:
  name: prometheus
spec:
  endOfLife:
    identifier: prometheus
  versionStreamFormat: ${{name}}-${{versions.major}}.${{versions.minor}}