apiVersion: versions.wolfi.dev/v1
kind: VersionStream
metadata:
  name: rabbitmq
spec:
  endOfLife:
    identifier: rabbitmq
  versionStreamFormat: ${{name}}-${{versions.major}}.${{versions.minor}}
status:
  eolVersions:
  - eolDate: "2023-12-31"
    releaseDate: "2022-09-26"
    version: "3.11"
  - eolDate: "2023-07-31"
    releaseDate: "2022-05-03"
    version: "3.10"
  - eolDate: "2023-01-31"
    releaseDate: "2021-07-23"
    version: "3.9"
  - eolDate: "2022-07-31"
    releaseDate: "2019-10-01"
    version: "3.8"
  - eolDate: "2020-09-30"
    releaseDate: "2017-11-28"
    version: "3.7"
  - eolDate: "2018-05-31"
    releaseDate: "2015-12-22"
    version: "3.6"
  - eolDate: "2016-10-31"
    releaseDate: "2015-03-11"
    version: "3.5"
  - eolDate: "2015-10-31"
    releaseDate: "2014-10-21"
    version: "3.4"
  - eolDate: "2015-03-31"
    releaseDate: "2014-04-02"
    version: "3.3"
  - eolDate: "2014-10-31"
    releaseDate: "2013-10-23"
    version: "3.2"
  - eolDate: "2014-04-30"
    releaseDate: "2013-05-01"
    version: "3.1"
  - eolDate: "2013-11-30"
    releaseDate: "2012-11-19"
    version: "3.0"
  lastUpdatedTimestamp: "2024-02-21T07:30:19.306742389Z"
  latestVersion: 3.12.13
  versions:
  - eolDate: "2024-06-30"
    releaseDate: "2023-06-01"
    version: "3.12"
