apiVersion: versions.wolfi.dev/v1
kind: VersionStream
metadata:
  name: telegraf
spec:
  endOfLife:
    identifier: telegraf
  versionStreamFormat: ${{name}}-${{versions.major}}.${{versions.minor}}
status:
  eolVersions:
  - eolDate: "2023-12-11"
    releaseDate: "2023-06-12"
    version: "1.27"
  - eolDate: "2023-09-11"
    releaseDate: "2023-03-13"
    version: "1.26"
  - eolDate: "2023-06-12"
    releaseDate: "2022-12-12"
    version: "1.25"
  - eolDate: "2023-03-13"
    releaseDate: "2022-09-12"
    version: "1.24"
  - eolDate: "2022-12-12"
    releaseDate: "2022-06-13"
    version: "1.23"
  - eolDate: "2022-09-12"
    releaseDate: "2022-03-23"
    version: "1.22"
  - eolDate: "2022-06-13"
    releaseDate: "2021-12-15"
    version: "1.21"
  - eolDate: "2022-03-23"
    releaseDate: "2021-09-17"
    version: "1.20"
  - eolDate: "2021-12-15"
    releaseDate: "2021-06-17"
    version: "1.19"
  - eolDate: "2021-09-17"
    releaseDate: "2021-03-17"
    version: "1.18"
  - eolDate: "2021-06-17"
    releaseDate: "2020-12-18"
    version: "1.17"
  - eolDate: "2021-03-17"
    releaseDate: "2020-10-21"
    version: "1.16"
  - eolDate: "2020-12-18"
    releaseDate: "2020-07-22"
    version: "1.15"
  - eolDate: "2020-10-21"
    releaseDate: "2020-03-26"
    version: "1.14"
  - eolDate: "2020-07-22"
    releaseDate: "2019-12-12"
    version: "1.13"
  - eolDate: "2020-03-26"
    releaseDate: "2019-09-03"
    version: "1.12"
  - eolDate: "2019-12-12"
    releaseDate: "2019-06-11"
    version: "1.11"
  - eolDate: "2019-09-03"
    releaseDate: "2019-03-05"
    version: "1.10"
  - eolDate: "2019-06-11"
    releaseDate: "2018-11-20"
    version: "1.9"
  - eolDate: "2019-03-05"
    releaseDate: "2018-09-21"
    version: "1.8"
  - eolDate: "2018-11-20"
    releaseDate: "2018-06-12"
    version: "1.7"
  - eolDate: "2018-09-21"
    releaseDate: "2018-04-16"
    version: "1.6"
  - eolDate: "2018-06-12"
    releaseDate: "2017-12-14"
    version: "1.5"
  - eolDate: "2018-04-16"
    releaseDate: "2017-09-05"
    version: "1.4"
  - eolDate: "2017-12-14"
    releaseDate: "2017-05-15"
    version: "1.3"
  - eolDate: "2017-09-05"
    releaseDate: "2017-01-23"
    version: "1.2"
  - eolDate: "2017-05-15"
    releaseDate: "2016-11-08"
    version: "1.1"
  - eolDate: "2017-01-23"
    releaseDate: "2016-09-02"
    version: "1.0"
  lastUpdatedTimestamp: "2024-02-21T07:30:19.309655599Z"
  latestVersion: 1.29.4
  versions:
  - eolDate: ""
    releaseDate: "2023-12-11"
    version: "1.29"
  - eolDate: ""
    releaseDate: "2023-09-11"
    version: "1.28"
